DROP TABLE IF EXISTS FENGYU_PL_Email_Account_Legacy;
ALTER TABLE FENGYU_PL_Email_Account RENAME TO FENGYU_PL_Email_Account_Legacy;
CREATE TABLE FENGYU_PL_Email_Account (id INTEGER PRIMARY KEY AUTOINCREMENT, display_name VARCHAR(200) NOT NULL, email VARCHAR(320) NOT NULL UNIQUE, encrypted_password TEXT NOT NULL, smtp_host VARCHAR(255) NOT NULL, smtp_port INTEGER NOT NULL, smtp_security VARCHAR(20) NOT NULL, imap_host VARCHAR(255), imap_port INTEGER, imap_security VARCHAR(20), is_default INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO FENGYU_PL_Email_Account SELECT id,display_name,email,encrypted_password,smtp_host,smtp_port,smtp_security,imap_host,imap_port,imap_security,is_default,CASE WHEN created_at='CURRENT_TEXT' THEN CURRENT_TIMESTAMP ELSE created_at END FROM FENGYU_PL_Email_Account_Legacy;
DROP TABLE FENGYU_PL_Email_Account_Legacy;
DROP TABLE IF EXISTS FENGYU_PL_Email_Contact_Legacy;
ALTER TABLE FENGYU_PL_Email_Contact RENAME TO FENGYU_PL_Email_Contact_Legacy;
CREATE TABLE FENGYU_PL_Email_Contact (id INTEGER PRIMARY KEY AUTOINCREMENT, email VARCHAR(320) NOT NULL UNIQUE, nickname VARCHAR(200), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO FENGYU_PL_Email_Contact SELECT id,email,nickname,CASE WHEN created_at='CURRENT_TEXT' THEN CURRENT_TIMESTAMP ELSE created_at END FROM FENGYU_PL_Email_Contact_Legacy;
DROP TABLE FENGYU_PL_Email_Contact_Legacy;
DROP TABLE IF EXISTS FENGYU_PL_Email_Mass_Config_Legacy;
ALTER TABLE FENGYU_PL_Email_Mass_Config RENAME TO FENGYU_PL_Email_Mass_Config_Legacy;
CREATE TABLE FENGYU_PL_Email_Mass_Config (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(200) NOT NULL, mode VARCHAR(30) NOT NULL, config_json TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO FENGYU_PL_Email_Mass_Config SELECT id,name,mode,config_json,CASE WHEN created_at='CURRENT_TEXT' THEN CURRENT_TIMESTAMP ELSE created_at END FROM FENGYU_PL_Email_Mass_Config_Legacy;
DROP TABLE FENGYU_PL_Email_Mass_Config_Legacy;
DROP TABLE IF EXISTS FENGYU_PL_Email_Pending_Send_Legacy;
ALTER TABLE FENGYU_PL_Email_Pending_Send RENAME TO FENGYU_PL_Email_Pending_Send_Legacy;
CREATE TABLE FENGYU_PL_Email_Pending_Send (id INTEGER PRIMARY KEY AUTOINCREMENT, confirmation_id VARCHAR(64) NOT NULL UNIQUE, account_id BIGINT NOT NULL, mode VARCHAR(30) NOT NULL, snapshot_json TEXT NOT NULL, status VARCHAR(20) NOT NULL, expires_at TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO FENGYU_PL_Email_Pending_Send SELECT id,confirmation_id,account_id,mode,snapshot_json,status,expires_at,CASE WHEN updated_at='CURRENT_TEXT' THEN CURRENT_TIMESTAMP ELSE updated_at END FROM FENGYU_PL_Email_Pending_Send_Legacy;
DROP TABLE FENGYU_PL_Email_Pending_Send_Legacy;
DROP TABLE IF EXISTS FENGYU_PL_Email_Sent_Log_Legacy;
ALTER TABLE FENGYU_PL_Email_Sent_Log RENAME TO FENGYU_PL_Email_Sent_Log_Legacy;
CREATE TABLE FENGYU_PL_Email_Sent_Log (id INTEGER PRIMARY KEY AUTOINCREMENT, confirmation_id VARCHAR(64), account_email VARCHAR(320) NOT NULL, recipients_json TEXT NOT NULL, subject VARCHAR(998), attachment_json TEXT, status VARCHAR(20) NOT NULL, error_message TEXT, sent_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO FENGYU_PL_Email_Sent_Log SELECT id,confirmation_id,account_email,recipients_json,subject,attachment_json,status,error_message,CASE WHEN sent_at='CURRENT_TEXT' THEN CURRENT_TIMESTAMP ELSE sent_at END FROM FENGYU_PL_Email_Sent_Log_Legacy;
DROP TABLE FENGYU_PL_Email_Sent_Log_Legacy;
CREATE INDEX FENGYU_PL_Email_Sent_Status_Idx ON FENGYU_PL_Email_Sent_Log(status, sent_at);
DROP TABLE IF EXISTS FENGYU_PL_Email_Schema_History_Legacy;
ALTER TABLE FENGYU_PL_Email_Schema_History RENAME TO FENGYU_PL_Email_Schema_History_Legacy;
CREATE TABLE FENGYU_PL_Email_Schema_History (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO FENGYU_PL_Email_Schema_History SELECT version,CASE WHEN applied_at='CURRENT_TEXT' THEN CURRENT_TIMESTAMP ELSE applied_at END FROM FENGYU_PL_Email_Schema_History_Legacy;
DROP TABLE FENGYU_PL_Email_Schema_History_Legacy;
INSERT INTO FENGYU_PL_Email_Schema_History(version,applied_at) VALUES (3,CURRENT_TIMESTAMP);
